import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Link from "next/link";

const stackComponents: {
  title: string;
  description: string;
  documentationUrl: string;
  exampleUrl?: string;
}[] = [
  {
    title: "Next.js",
    description: "The React framework for production.",
    documentationUrl: "https://nextjs.org/",
  },
  {
    title: "TypeScript",
    description:
      "Strongly typed programming language that builds on JavaScript, giving you better tooling at any scale.",
    documentationUrl: "https://www.typescriptlang.org/",
  },
  {
    title: "TailwindCSS",
    description: "Rapidly build modern websites without ever leaving your HTML.",
    documentationUrl: "https://tailwindcss.com/",
  },
  {
    title: "tRPC",
    description: "End-to-end typesafe APIs made easy.",
    documentationUrl: "https://trpc.io/",
    exampleUrl: "/examples/trpc",
  },
  {
    title: "NextAuth.js",
    description: "Authentication built for Next.js.",
    documentationUrl: "https://next-auth.js.org/",
    exampleUrl: "/examples/auth",
  },
  {
    title: "Playwright",
    description: "Fast and reliable end-to-end testing for modern web apps.",
    documentationUrl: "https://playwright.dev/",
  },
];

const Index: NextPage = () => (
  <>
    <Head>
      <title>Full Stack Blocks</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className="flex w-screen flex-col items-center justify-center p-4">
      <h1 className="text-5xl font-extrabold text-slate-700 md:text-7xl lg:text-7xl">Full Stack Blocks</h1>
      <p className="mb-6 text-4xl font-semibold text-slate-700 md:text-6xl lg:text-6xl">Core</p>
      <a
        href="https://github.com/Dennitz/fullstackblocks-core"
        className="mb-10 font-semibold text-indigo-600 hover:text-indigo-500"
      >
        Documentation
      </a>
      <p className="mb-3 text-2xl text-slate-700">This stack uses</p>
      <div className="grid w-full grid-cols-1 grid-rows-3 items-center justify-center gap-3 pt-3 md:w-full md:grid-cols-2 md:grid-rows-2 lg:w-2/3 lg:grid-cols-2 lg:grid-rows-2">
        {stackComponents.map((details) => (
          <div
            key={details.title}
            className="flex h-full w-full cursor-pointer flex-col items-center justify-center rounded-md bg-white px-8 py-4 text-center shadow-md"
            data-test-id="stack-component"
          >
            <h2 className="mb-1 text-lg font-semibold text-slate-800">{details.title}</h2>
            <p className="mb-2 text-sm text-slate-600">{details.description}</p>
            <div>
              <a
                className="text-sm font-semibold text-indigo-600 hover:text-indigo-500"
                href={details.documentationUrl}
                target="_blank"
                rel="noreferrer"
              >
                Documentation
              </a>
              {details.exampleUrl && (
                <Link href={details.exampleUrl}>
                  <a className="ml-5 text-sm font-semibold text-indigo-600 hover:text-indigo-500">Example</a>
                </Link>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  </>
);

export default Index;
